title: codingINDIAN
slogan: all you need to kNow
logo: "custom – 1@3x.png"

#baseurl: ""
url: "https://www.codingindian.codes"

timezone: UTC

collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  notes:
    title: Notes
    output: true    

defaults:
- scope:
    path: _posts
  values:
    layout: post
    author: Sharad Raj
- scope:
    path: _notes
  values:
    permalink: notes/:categories/:year/:month/:day/:title:output_ext
    layout: post
    author: Sharad Raj

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jemoji
  - jekyll-paginate
  - kramdown

markdown: kramdown
paginate: 5
paginate_path: "/page:num"